version: 0.2

phases:
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build:ci

artifacts:
  bade-directory: 'dist/travis-example'
  discard-paths: yes
  files:
    - '**/*.js'
    - '**/*.css'
    - '**/*.html'
    - '**/*.ico'

