version: 0.2

phases:
  install:
    commands:

      # Upgrade apt
      - apt-get upgrade

      # Update libs
      - apt-get update

      # Install apt-transport-https
      - apt-get install -y apt-transport-https

      # Use apt to install the Chrome dependencies
      - apt-get install -y libxcursor1
      - apt-get install -y libgtk-3-dev
      - apt-get install -y libxss1
      - apt-get install -y libasound2
      - apt-get install -y libnspr4
      - apt-get install -y libnss3
      - apt-get install -y libx11-xcb1

      # Print out missing libs
      - echo "Missing Libs" || ldd ./node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome | grep not


  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build:ci
      - npm run test:ci

artifacts:
  base-directory: 'dist/travis-example'
  discard-paths: yes
  files:
    - '**/*.js'
    - '**/*.css'
    - '**/*.html'
    - '**/*.ico'

