AWSTemplateFormatVersion: "2010-09-09"
Description: This template will create the S3 bucket that will host the angular application

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name to fulfill S3 bucket
    MinLength: 3
    MaxLength: 48
    AllowedPattern: ^[a-z]*$
    ConstraintDescription: Environment name must be lowercase only and between 3 and 48 characters.

Resources:
  AngularAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub avishco-angular-${EnvironmentName}
      Tags:
        - Key: Application Name
          Value: Angular DevOps
        - Key: Company
          Value: avishco
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

Outputs:
  WebsiteURL:
    Value: !GetAtt [AngularAppBucket, WebsiteURL]
    Description: URL of the website
